import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import { ChakraBaseProvider } from "@chakra-ui/react";
import theme from "@/config/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraBaseProvider theme={theme}>{children}</ChakraBaseProvider>
      </body>
    </html>
  );
}
